### ISSUE TITLE
Multi-language Code Blocks

### ISSUE THREAD

**Issue by artlogic** [arsmentis/volt-docs#20]

**Comment by nsbasic** [comment]
Looks great!

**Comment by artlogic** [comment]
Here's what the proposed code would look like for a multi-language block:

```
<div class="code-tabs" data-languages="Python,JavaScript">

{% highlight python %}
print('howdy!')
{% endhighlight %}

{% highlight javascript %}
console.log('howdy!');
{% endhighlight %}

</div>
```

The next step is to write a bit of jQuery that selects every `.code-tabs` and adds the proper HTML to create tabs, roughly:

1. Wrap each `<figure></figure>` in `<div role="tabpanel" class="tab-pane" id="code-tabs-N"></div>` (replace `N` with the value of a global counter)
2. Add an additional class to the first `figure`'s wrapper: `active`
3. Wrap all the `div.tabpanel`s in `<div class="tab-content"></div>`
4. Create a `<ul class="nav nav-tabs" role="tablist"></ul>` above the `div.tab-content` still inside of `div.code-tabs`.
5. NEEDS WORK: For each comma separated entry in data-languages, add: `<li role="presentation"><a href="#code-tabs-N" aria-controls="code-tabs-N" role="tab" data-toggle="tab">Language Name</a></li>` (replace `N` with the same `N` values used above)
6. Add an additional class to the first `li`: `active`
7. Run the following code:

    ```javascript
    $('.code-tabs a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
    });
    ```

8. Make sure the following CSS is included:

    ```css
    .code-tabs pre {
      border-top: 0;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
      border-color: #ddd;
    }
    .code-tabs ul.nav-tabs li.active a { background-color: #f5f5f5 }
    .code-tabs ul.nav-tabs li.active a:focus { background-color: #f5f5f5 }
    .code-tabs ul.nav-tabs li.active a:hover { background-color: #f5f5f5 }
    .code-tabs ul.nav-tabs li a:hover { background-color: #f9f9f9 }
    ```
